---
title: "Calgary"
author: "Olivier Haley"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(httr)
library(tidyverse)
library(rvest)
library(jsonlite)
library(tidyr)
library(RSelenium)
```


```{r}
fig.title = "Calgary Incidents"
url = "https://data.calgary.ca/Transportation-Transit/Traffic-Incidents/35ra-9556"
# Define month and year of expiry
m = "Jun"
y = 2023
# Start RSelenium and Navigate to the page
#binman::rm_platform("phantomjs")
#wdman::selenium(retcommand = TRUE)
rD <- rsDriver(browser = "firefox", chromever = NULL, verbose = FALSE)
remDr <- rD$client
rD$server$log()
remDr$open()
remDr$navigate(url)
Sys.sleep(2)
# find the right elements in Developer Mode
# this is the "select class = "Fz(s) H(25px) Bd Bdc($seperatorColor)" heading
download_button <- remDr$findElement(using = 'xpath', '/html/body/main/div/div[1]/div/div[1]/div/div/div[1]/div/div[2]/div/div[2]/button')
download_button$clickElement()

path_1 <- remDr$findElement(using = 'xpath', '/html/body/main/div/div[1]/div/div[1]/div/div/div[1]/div/div[2]/div/div[2]/div/section/ul/li[1]/a') 

get <- path_1$getElementAttribute("href")
url_1 <- get[[1]]

df_crash <- read.csv(url(url_1))
# Close the connection the last time in your .Rmd you are using it.
remDr$close()
rD[["server"]]$stop()
df_crash
```

```{r}
url_w = "https://calgary.weatherstats.ca/download.html"
r <- POST(url_w, body = list(limit = 1000, type = "normal_monthly", submit = "Downlaod", formdata = "ok"), encode = "form") 
r
all_weather_df <- read.csv(text = content(r, "text"), stringsAsFactors = FALSE)
```

```{r}
weather_df <- all_weather_df %>% 
  dplyr::mutate(date = format(as.Date(date, format = "%Y-%m-%d"), "%Y-%m")) %>% 
  dplyr::select(date, "min_temperature_v", "snow_on_ground_v")
weather_df

```


```{r}
df <- x %>% 
  dplyr::mutate(date = format(as.Date(START_DT, format = "%Y/%m/%d"), "%Y-%m-%d")) %>% 
  dplyr::filter(date <= as.Date("2023-03-31")) %>% 
  dplyr::mutate(date = format(as.Date(date, format = "%Y-%m-%d"), "%Y-%m")) %>% 
  dplyr::select(date, Count) %>% 
  group_by(date) %>% 
  summarise(count = n()) %>% 
  na.omit()
df
x
```


```{r}
complete_df <- merge(df, weather_df, by = "date", all = TRUE) %>% 
  na.omit() %>% 
  subset(count!=1)
complete_df
```







